export const AUDIO_NODE_KEYS = [
  "AnalyserNode",
  "AudioBufferSourceNode",
  "AudioDestinationNode",
  "AudioScheduledSourceNode",
  "AudioWorkletNode",
  "BiquadFilterNode",
  "ChannelMergerNode",
  "ChannelSplitterNode",
  "ConstantSourceNode",
  "ConvolverNode",
  "DelayNode",
  "DynamicsCompressorNode",
  "GainNode",
  "IIRFilterNode",
  "MediaElementAudioSourceNode",
  "MediaStreamAudioDestinationNode",
  "MediaStreamAudioSourceNode",
  "OscillatorNode",
  "PannerNode",
  "ScriptProcessorNode",
  "StereoPannerNode",
  "WaveShaperNode",
] as const
