export type NativeAudioNode = AudioNode
export type NativeAudioParam = AudioParam
export type NativeBaseAudioContext = BaseAudioContext
export type NativeAudioContext = AudioContext
export type NativeOfflineAudioContext = OfflineAudioContext
export type NativeAudioBuffer = AudioBuffer
export type NativeAudioBufferSourceNode = AudioBufferSourceNode
export type NativeAudioDestinationNode = AudioDestinationNode
export type NativeAudioListener = AudioListener
export type NativeAudioWorkletNode = AudioWorkletNode
export type NativeAudioWorkletProcessor = AudioWorkletProcessor
export type NativeBiquadFilterNode = BiquadFilterNode
export type NativeChannelMergerNode = ChannelMergerNode
export type NativeChannelSplitterNode = ChannelSplitterNode
export type NativeConstantSourceNode = ConstantSourceNode
export type NativeConvolverNode = ConvolverNode
export type NativeDelayNode = DelayNode
export type NativeDynamicsCompressorNode = DynamicsCompressorNode
export type NativeGainNode = GainNode
export type NativeIIRFilterNode = IIRFilterNode
export type NativeMediaElementAudioSourceNode = MediaElementAudioSourceNode
export type NativeMediaStreamAudioDestinationNode =
  MediaStreamAudioDestinationNode
export type NativeMediaStreamAudioSourceNode = MediaStreamAudioSourceNode
export type NativeOscillatorNode = OscillatorNode
export type NativePannerNode = PannerNode
export type NativePeriodicWave = PeriodicWave
export type NativeStereoPannerNode = StereoPannerNode
export type NativeWaveShaperNode = WaveShaperNode
export type NativeAnalyserNode = AnalyserNode
export type NativeAudioScheduledSourceNode = AudioScheduledSourceNode
export type NativeAudioWorklet = AudioWorklet
export type NativeAudioWorkletGlobalScope = AudioWorkletGlobalScope
export type NativeAudioWorkletProcessorConstructor =
  AudioWorkletProcessorConstructor
export type NativeAudioParamMap = AudioParamMap
export type NativeMediaStream = MediaStream
export type NativeMediaStreamTrack = MediaStreamTrack
export type NativeScriptProcessorNode = ScriptProcessorNode
export type NativeOfflineAudioCompletionEvent = OfflineAudioCompletionEvent
