name: Run Checks

on:
  workflow_call:

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Persisted Project"
        uses: actions/download-artifact@v3
        with:
          name: project
      - run: pwd && ls
      - name: "Run checks"
        id: "run-checks"
        run: "npm run check-all"
