name: Run Checks

on:
  workflow_call:

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Persisted Project"
        id: persist-project
        uses: actions/cache@v3
        with:
          path: ./*
          key: project-${{ github.sha }}
      - run: pwd && ls
      - name: "Run checks"
        id: "run-checks"
        run: "npm run check-all"
