name: Run Checks

on:
  workflow_call:

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls
      - name: "Run checks"
        id: "run-checks"
        run: "npm run check-all"
