# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Run Checks

on:
  - workflow_call
  - workflow_dispatch

jobs:
  setup_project:
    uses: ./.github/workflows/setup_project.yml
  run_checks:
    needs: setup_project
    name: "Run Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Get Persisted Project"
        id: get-project
        uses: actions/cache@v3
        with:
          path: ./*
          key: project-${{ github.sha }}
      - name: "Run checks"
        id: "run-checks"
        run: "npm run check-all"
